/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
* File Name: sys-11-definitions.inc
*
* Type: DEFINITIONS
*
* Title: System related definitions
*
* Version: 1.1
*
* Purpose:
*
* Date first created: 11th October 2015
* Date last modified: 11th October 2015
*
* Author: John Scott
*
* Used by: sys-11.inc
*
*
*
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

; ========================== DEFINITIONS =============================

