/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
* File Name: usb-21-debug.inc
*
* Type: SOURCE
*
* Title: USB Debug Routines
*
* Version: 2.1
*
* Purpose: This file contains the data initialisation to place USB
*          related information in the device memory. The content to
*          be placed in the memory is written into the relevant
*          OPTION file (usb-21-option-info.inc).
*
* Date first created: 11th October 2015
* Date last modified: 11th October 2015
*
* Author: John Scott
*
* Used by: usb-21.inc
*
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */


