/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
* File Name: extern-11.inc
*
* Type: extern declarations
*
* Title: Declaration of externel variables
*
* Version: 1.1
*
* Purpose:
*
* Date first created: 11th October 2015
* Date last modified: 25th January 2017
*
* Author: John Scott
*
* Used by: usb-21.s
*
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

;.extern CTword
.extern CTword
    