/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
* File Name: io-11-const.inc
*
* Type: Definition
*
* Title: Constant symbol definitions
*
* Version: 1.1
*
* Purpose: To be included with all IO source files
*
* Date first created: 26th January 2017
* Date last modified: 26th January 2017
*
* Author: John Scott
*
* Used by: io-11.s
*
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

; ========================== DEFINITIONS =============================


; Port D line map for input/output
.equiv  red,    0
.equiv  amber,  1
.equiv  green,  2

.equiv  SW1,    6
.equiv  SW2,    7
.equiv  SW3,    13
